"""
analysis/comparison.py
======================
Cross-fitting comparison: every model fits data generated by every other model.

This is the correct answer to the methodological question:
"Is Model X better at recovering parameters than Model Y *on the same IGT task*?"

Key design decisions
--------------------
* Data is generated by a *data-generating config* (DGC) using its own parameter space.
* Every *fitting config* (FC) then fits that same sequence of actions/outcomes.
* Because models have different parameter spaces, we can only compare:
    - NLL (negative log-likelihood) — lower = better fit to the data
    - BIC / AIC — penalised likelihood, accounts for different n_params
    - Within-model RMSSE — only meaningful when DGC == FC (true parameter recovery)
    - Between-model RMSSE is NOT computed (parameters are incommensurable)

The main output is a DataFrame with one row per (data_agent, fit_agent, sample) triple.

Usage
-----
    from config import AGENT_CONFIGS
    from analysis.comparison import run_cross_fit_comparison
    from plots.comparison import plot_cross_fit_results

    df = run_cross_fit_comparison(
        configs=list(AGENT_CONFIGS.values()),
        n_agents=200,        # synthetic participants per data-generating model
        n_trials=100,        # IGT trials per participant
        n_repeats=5,         # independent fits per (data, fit_model) pair — for variance
        seed=42,
    )
    plot_cross_fit_results(df, output_dir=Path("outputs/comparison"))
"""

from __future__ import annotations

import numpy as np
import pandas as pd
from joblib import Parallel, delayed
from tqdm import tqdm

from environment.igt_env import get_lhs_samples, Environment
from analysis.fitting import nll, fit_model


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _generate_data_bechara(params, dgc, n_trials: int, seed=None):
    """Generate IGT data using the ORIGINAL Bechara payoff structure.

    This replaces the stochastic Environment with EnvironmentBechara so that
    results are directly comparable with published literature (Haines 2018,
    Steingroever 2013, Ligneul 2019 all use this structure).
    """
    from environment.igt_env import EnvironmentBechara

    rng = np.random.default_rng(seed)
    env = EnvironmentBechara()
    decks = env.create_live_game_decks()

    agent = dgc.create_agent(params, horizon=0, rng=rng)

    actions, outcomes = [], []
    counts = {0: 0, 1: 0, 2: 0, 3: 0}
    d_map = {0: "A", 1: "B", 2: "C", 3: "D"}

    for _ in range(n_trials):
        a = agent.act()
        d_char = d_map[a]
        card = decks[d_char][counts[a] % len(decks[d_char])]
        counts[a] += 1
        agent.update(a, card)
        actions.append(a)
        outcomes.append(card)

    return actions, outcomes


def _bic(neg_log_like: float, n_params: int, n_trials: int) -> float:
    return 2 * neg_log_like + n_params * np.log(n_trials)


def _aic(neg_log_like: float, n_params: int) -> float:
    return 2 * neg_log_like + 2 * n_params


def _one_cross_fit(
    sample_idx: int,
    true_params: np.ndarray,
    dgc,          # data-generating AgentConfig
    fc,           # fitting AgentConfig
    n_trials: int,
    seed: int,
    n_fit_starts: int = 10,
):
    """Single unit of work: generate data from dgc, fit with fc.

    Returns a dict with all metrics for this (sample, dgc, fc) triple.
    """
    # ── 1. Generate data ────────────────────────────────────────────────────
    actions, outcomes = _generate_data_bechara(true_params, dgc, n_trials, seed=seed)

    # ── 2. Fit with the fitting config ──────────────────────────────────────
    # More starts than the default 4 — important for fair comparison
    rng = np.random.default_rng(seed + 99999)
    fit_starts = [list(fc.default_test_params)] if fc.default_test_params else []
    for _ in range(n_fit_starts - len(fit_starts)):
        fit_starts.append([rng.uniform(b[0], b[1]) for b in fc.bounds])

    from scipy.optimize import minimize
    best_nll = np.inf
    best_params = None

    for x0 in fit_starts:
        res = minimize(
            nll, x0,
            args=(actions, outcomes, fc, 0),
            bounds=fc.bounds,
            method="L-BFGS-B",
        )
        if res.success and res.fun < best_nll:
            best_nll = res.fun
            best_params = res.x

    if best_params is None:
        return None  # fit failed entirely

    n_params_fit = len(fc.bounds)
    record = {
        "sample_idx":   sample_idx,
        "data_model":   dgc.name,
        "fit_model":    fc.name,
        "nll":          float(best_nll),
        "bic":          float(_bic(best_nll, n_params_fit, n_trials)),
        "aic":          float(_aic(best_nll, n_params_fit)),
        "n_params_fit": n_params_fit,
        "n_trials":     n_trials,
        "fit_success":  True,
    }

    # ── 3. RMSSE — only meaningful when data_model == fit_model ─────────────
    if dgc.name == fc.name and best_params is not None:
        ranges = np.array([b[1] - b[0] for b in fc.bounds])
        scaled = np.abs(best_params - true_params) / ranges
        rmsse = float(np.sqrt(np.mean(scaled ** 2)))
        record["rmsse"] = rmsse

        # Per-parameter scaled errors (for the self-fit case)
        for i, name in enumerate(fc.param_names):
            record[f"true_{name}"] = float(true_params[i])
            record[f"est_{name}"]  = float(best_params[i])
            record[f"err_{name}"]  = float((best_params[i] - true_params[i]) / ranges[i])
    else:
        record["rmsse"] = np.nan

    return record


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def run_cross_fit_comparison(
    configs: list,
    n_agents: int = 200,
    n_trials: int = 100,
    n_repeats: int = 3,
    n_fit_starts: int = 10,
    seed: int = 42,
) -> pd.DataFrame:
    """Run full cross-fitting comparison across all models.

    For each data-generating config (DGC):
      1. Sample n_agents parameter vectors via LHS from DGC's parameter space.
      2. For each parameter vector, generate n_repeats independent IGT datasets
         using the Bechara payoff structure.
      3. Fit ALL configs (including DGC itself) to each dataset.

    This produces a complete matrix of (data_model × fit_model) comparisons
    on identical behavioural data.

    Args:
        configs:       list of AgentConfig objects to compare
        n_agents:      number of synthetic participants per DGC
        n_trials:      IGT trials per participant (100 = standard)
        n_repeats:     independent fits per agent per fit_model (for variance estimation)
        n_fit_starts:  L-BFGS-B starting points per fit (>=10 recommended)
        seed:          base RNG seed

    Returns:
        DataFrame with columns:
            sample_idx, data_model, fit_model,
            nll, bic, aic, n_params_fit, n_trials, fit_success,
            rmsse (NaN when data_model != fit_model),
            true_{name}, est_{name}, err_{name}  (only when data_model == fit_model)
    """
    rng = np.random.default_rng(seed)

    # Build task list: (sample_idx, true_params, dgc, fc, seed_i)
    tasks = []
    for dgc in configs:
        param_samples = get_lhs_samples(n_agents, dgc.bounds, seed=seed)
        for agent_idx, true_p in enumerate(param_samples):
            for rep in range(n_repeats):
                task_seed = int(rng.integers(0, 2**31))
                for fc in configs:
                    tasks.append((agent_idx * n_repeats + rep, true_p, dgc, fc, task_seed))

    total = len(tasks)
    print(f"\nCross-fit comparison: {len(configs)} models × {n_agents} agents "
          f"× {n_repeats} repeats = {total} fits total\n")

    raw = Parallel(n_jobs=-1, verbose=5)(
        delayed(_one_cross_fit)(
            t[0], t[1], t[2], t[3], n_trials, t[4], n_fit_starts
        )
        for t in tqdm(tasks, desc="Cross-fitting")
    )

    records = [r for r in raw if r is not None]
    if not records:
        raise RuntimeError("All fits failed — check model configurations.")

    df = pd.DataFrame(records)
    n_failed = total - len(records)
    if n_failed > 0:
        print(f"Warning: {n_failed}/{total} fits failed ({n_failed/total*100:.1f}%)")

    return df


def summarize_cross_fit(df: pd.DataFrame) -> pd.DataFrame:
    """Compute summary statistics per (data_model, fit_model) pair.

    Returns a DataFrame with one row per pair, suitable for a comparison table.
    """
    groups = df.groupby(["data_model", "fit_model"])

    rows = []
    for (dgc_name, fc_name), grp in groups:
        row = {
            "data_model":    dgc_name,
            "fit_model":     fc_name,
            "n":             len(grp),
            "nll_mean":      grp["nll"].mean(),
            "nll_std":       grp["nll"].std(),
            "bic_mean":      grp["bic"].mean(),
            "aic_mean":      grp["aic"].mean(),
            "fail_rate":     1.0 - grp["fit_success"].mean(),
        }
        if dgc_name == fc_name:
            row["rmsse_median"] = grp["rmsse"].median()
            row["rmsse_p90"]    = grp["rmsse"].quantile(0.90)
        else:
            row["rmsse_median"] = np.nan
            row["rmsse_p90"]    = np.nan
        rows.append(row)

    summary = pd.DataFrame(rows)
    summary = summary.sort_values(["data_model", "bic_mean"])
    return summary


def best_fitting_model_per_agent(df: pd.DataFrame) -> pd.DataFrame:
    """For each (data_model, sample_idx), find which fit_model achieves lowest BIC.

    This answers: "When participant data is generated by Model X,
    which model does the data prefer according to BIC?"

    A well-identified model should win on its own data.
    A poorly-identified model may be beaten by a simpler competitor.

    Returns DataFrame with columns:
        data_model, sample_idx, best_fit_model, best_bic, true_model_bic,
        true_model_rank (1 = best, higher = worse)
    """
    rows = []
    for (dgc_name, sample_idx), grp in df.groupby(["data_model", "sample_idx"]):
        # Average BIC across repeats per fit_model
        bic_per_model = grp.groupby("fit_model")["bic"].mean()
        ranked = bic_per_model.sort_values()

        best_model = ranked.index[0]
        best_bic   = ranked.iloc[0]
        true_bic   = bic_per_model.get(dgc_name, np.nan)
        true_rank  = (list(ranked.index).index(dgc_name) + 1
                      if dgc_name in ranked.index else np.nan)

        rows.append({
            "data_model":      dgc_name,
            "sample_idx":      sample_idx,
            "best_fit_model":  best_model,
            "best_bic":        best_bic,
            "true_model_bic":  true_bic,
            "true_model_rank": true_rank,
            "true_model_wins": best_model == dgc_name,
        })

    return pd.DataFrame(rows)